set-option -g mouse on
set -g mouse on
set -g terminal-overrides 'xterm*:smcup@:rmcup@'

set -g default-terminal 'tmux-256color'
set -ga terminal-overrides ',xterm-256color:RGB'
set -ga terminal-overrides ',tmux-256color:RGB'

set -g status-bg magenta
set -g status-fg gray

set -g window-status-format " #I:#W"
set -g window-status-current-style "fg=magenta,bg=gray"
set -g window-status-current-format "❯#I:#W"

set -g status-left " [#S] "
set -g status-right "%Y/%m/%d %H:%M "

set -g pane-border-style fg=gray
set -g pane-active-border-style fg=magenta

set -g message-style "fg=gray,bg=magenta"

set -g mode-style "fg=black,bg=#ffffff"

# set -g copy-mode-match-style "fg=black,bg=white"
# set -g copy-mode-current-match-style "fg=black,bg=white"

set -s escape-time 0
set-window-option -g mode-keys vi

